PhotoPortfolio/PhotoPortfolio/Controllers/ExpenseCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoPortfolio.Models;

namespace PhotoPortfolio.Controllers
{
    public class ExpenseCategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ExpenseCategories
        public ActionResult Index()
        {
            return View(db.ExpenseCategories.ToList());
        }

        // GET: ExpenseCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseCategory expenseCategory = db.ExpenseCategories.Find(id);
            if (expenseCategory == null)
            {
                return HttpNotFound();
            }
            return View(expenseCategory);
        }

        // GET: ExpenseCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreatePartial()
        {
            return PartialView("Create");
        }

        // POST: ExpenseCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] ExpenseCategory expenseCategory)
        {
            if (ModelState.IsValid)
            {
                db.ExpenseCategories.Add(expenseCategory);
                db.SaveChanges();
                return RedirectToAction("Index", "Expenses");
            }

            return View(expenseCategory);
        }

        // GET: ExpenseCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseCategory expenseCategory = db.ExpenseCategories.Find(id);
            if (expenseCategory == null)
            {
                return HttpNotFound();
            }
            return View(expenseCategory);
        }

        // POST: ExpenseCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] ExpenseCategory expenseCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expenseCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expenseCategory);
        }

        // GET: ExpenseCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseCategory expenseCategory = db.ExpenseCategories.Find(id);
            if (expenseCategory == null)
            {
                return HttpNotFound();
            }
            return View(expenseCategory);
        }

        // POST: ExpenseCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExpenseCategory expenseCategory = db.ExpenseCategories.Find(id);
            db.ExpenseCategories.Remove(expenseCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhotoPortfolio/PhotoPortfolio/Controllers/RevenueCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoPortfolio.Models;

namespace PhotoPortfolio.Controllers
{
    public class RevenueCategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RevenueCategories
        public ActionResult Index()
        {
            return View(db.RevenueCategories.ToList());
        }

        // GET: RevenueCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RevenueCategory revenueCategory = db.RevenueCategories.Find(id);
            if (revenueCategory == null)
            {
                return HttpNotFound();
            }
            return View(revenueCategory);
        }

        // GET: RevenueCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreatePartial()
        {
            return PartialView("Create");
        }

        // POST: RevenueCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] RevenueCategory revenueCategory)
        {
            if (ModelState.IsValid)
            {
                db.RevenueCategories.Add(revenueCategory);
                db.SaveChanges();
                return RedirectToAction("Index", "Revenues");
            }

            return View(revenueCategory);
        }

        // GET: RevenueCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RevenueCategory revenueCategory = db.RevenueCategories.Find(id);
            if (revenueCategory == null)
            {
                return HttpNotFound();
            }
            return View(revenueCategory);
        }

        // POST: RevenueCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] RevenueCategory revenueCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(revenueCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(revenueCategory);
        }

        // GET: RevenueCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RevenueCategory revenueCategory = db.RevenueCategories.Find(id);
            if (revenueCategory == null)
            {
                return HttpNotFound();
            }
            return View(revenueCategory);
        }

        // POST: RevenueCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RevenueCategory revenueCategory = db.RevenueCategories.Find(id);
            db.RevenueCategories.Remove(revenueCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhotoPortfolio/PhotoPortfolio/Views/Shared/_ClientName.cshtml

@{
    ViewBag.Title = "_ClientName";
}

<h2>_ClientName</h2>


PhotoPortfolio/PhotoPortfolio/Views/Shared/_Layout.cshtml
@using PhotoPortfolio.Models
@using System.Data.Entity;
@using System.Linq;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @*<link href="~/Content/jquery.ui.base.css" rel="stylesheet" />
    <link href="~/Content/jquery.ui.core.css" rel="stylesheet" />
    <link href="~/Content/jquery.ui.theme.css" rel="stylesheet" />*@
    <link href="~/Content/bootstrap-datepicker.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/dropzonecss")
    @*<link rel="stylesheet" href="~/Content/reset.css">
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/style-responsive.css">*@
    <link href="~/Content/stylesheet.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    @Scripts.Render("~/bundles/Chart")
    @*@Scripts.Render("~/bundles/core")
    @Scripts.Render("~/bundles/widget")
    @Scripts.Render("~/bundles/datepicker")*@
    @Scripts.Render("~/bundles/dropzonescripts")
    @Scripts.Render("~/bundles/Stellar")

    @*<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">*@
    @*<script src="~/Scripts/js/jquery.min.js"></script>
    <script src="~/Scripts/js/jquery.easing.min.js"></script>
    <script src="~/Scripts/js/modernizr.custom.42534.js" type="text/javascript"></script>
    <script src="~/Scripts/js/jquery.waitforimages.js" type="text/javascript"></script>
    <script src="~/Scripts/js/typed.js" type="text/javascript"></script>
    <script src="~/Scripts/js/masonry.pkgd.min.js" type="text/javascript"></script>
    <script src="~/Scripts/js/imagesloaded.pkgd.min.js" type="text/javascript"></script>
    <script src="~/Scripts/js/jquery.jkit.1.2.16.min.js"></script>

    <script src="~/Scripts/js/script.js" type="text/javascript"></script>*@

  
   
</head>
<body>
    @*<div class="preloader" id="preloader">
        <div class="item">
            <div class="spinner">
            </div>
        </div>
    </div>

    <div class="opacity-nav">

        <div class="menu-index" id="buttons" style="z-index:999999">
            <i class="fa  fa-close"></i>
        </div>

        <ul class="menu-fullscreen">
            <li>@Html.ActionLink("Home", "Index", "Home"@*, new { @class="ajax-link"})</li>
            <li>@Html.ActionLink("Weddings", "Weddings", "Home", new { @class="ajax-link"})</li>
            @Html.Partial("_LoginPartial")*@
            @*<li><a class="ajax-link" href="index.html">Home</a></li>
            <li><a class="ajax-link" href="projects.html">Projects</a></li>
            <li><a class="ajax-link" href="about-us.html">About us</a></li>
            <li><a class="ajax-link" href="contact.html">Contact</a></li>*@
        @*</ul>

    </div>
    <header id="fullscreen">*@

        @*<div class="logo" id="full"><a class="ajax-link" href="index.html" style="color: #87C0D2; font-family:'madina_script-webfont'; text-transform:none">Love KC Photography</a></div>*@

        @*<div class="menu-index" id="button">
            <i class="fa fa-bars"></i>
        </div>

    </header>*@
    
    @*<div class="clear"></div>*@
        <div class="navbar navbar-inverse navbar-fixed-top ">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Love KC Photography", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Revenues", "Index", "Revenues")</li>
                        <li>@Html.ActionLink("Expenses", "Index", "Expenses")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>


    @if (User.Identity.IsAuthenticated)
    {
        ApplicationDbContext db = new ApplicationDbContext();

        <div class="navbar navbar-default" style="background:none">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar-collapse" style="text-align:center">
                    <ul >
                        <li class="btn btn-secondary">@Html.ActionLink("Revenue", "Index", "Revenues")</li>
                        <li class="btn btn-secondary">@Html.ActionLink("Expense", "Index", "Expenses")</li>
                        <li class="btn btn-secondary">@Html.ActionLink("RegisteredUsers", "Index", "RegisteredUsers")</li>
                        <li class="btn dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Manage Packages <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" >
                                <li class="dropdown-header">Create Categories</li>
                                <li>@Html.ActionLink("Revenue Categories", "Create", "RevenueCategories")</li>
                                <li>@Html.ActionLink("Expense Categories", "Create", "ExpenseCategories")</li>
                                <li class="divider"></li>
                                <li class="dropdown-header">My Packages</li>
                                <li><a href="#">Premium Package $3000</a></li>
                                <li><a href="#">Deluxe Package #2000</a></li>
                                <li><a href="#">Basic Package $1000</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    }
            @RenderBody()
    <footer>
        <p>&copy; @DateTime.Now.Year </p>
        <div class="footer-margin">
            <div class="social-footer">
                <a href="https://www.facebook.com/lovekcphotography"><i class="fa fa-facebook"></i></a>

            </div>
            @*<div class="copyright">© Copyright 2015. All Rights Reserved.</div>*@

        </div>
    </footer>

    <script>
        $(document).ready(function () {
            $.stellar();
        });

        $('#button, #buttons').on('click', function () {
            $(".opacity-nav").fadeToggle("slow", "linear");
            // Animation complete.
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>