PhotoPortfolio/PhotoPortfolio/Models/Revenue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoPortfolio.Models
{
    public class Revenue
    {

        public int ID { get; set; }
        public double? Total { get; set; }
        public DateTime Date { get; set; }

        public int RegisteredUserID { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
        public int RevenueCategoryID { get; set; }
        public virtual RevenueCategory RevenueCategory { get; set; }

    }
}

PhotoPortfolio/PhotoPortfolio/Models/RevenueViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace PhotoPortfolio.Models
{
    public class RevenueViewModel
    {
        [DisplayName("Client")]
        public RegisteredUser RegisteredUser { get; set; }
        public double? Total { get; set; }
        public DateTime Date { get; set; }
        public RevenueCategory RevenueCategory { get; set; }

    }
}

PhotoPortfolio/PhotoPortfolio/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoPortfolio.Models;
using Microsoft.AspNet.Identity;

namespace PhotoPortfolio.Controllers
{
    public class RegisteredUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RegisteredUsers
        public ActionResult Index()
        {
            return View(db.RegisteredUsers.ToList());
        }

        public ActionResult Landing()
        {
            return View();
        }

        // GET: RegisteredUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisteredUser RegisteredUser = db.RegisteredUsers.Find(id);
            if (RegisteredUser == null)
            {
                return HttpNotFound();
            }
            return View(RegisteredUser);
        }

        // GET: RegisteredUsers/Create
        public ActionResult CreatePartial()
        {
            return PartialView("Create");
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: RegisteredUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Firstname,Lastname,Address,City,State,ZipCode,Email,RegisteredUserID")] RegisteredUser RegisteredUser)
        {
            if (ModelState.IsValid)
            {
                RegisteredUser.RegisteredUserID = User.Identity.GetUserId();
                //ViewBag.ExpenseCategoryID = new SelectList(db.ExpenseCategories, "ID", "Name", expense.ExpenseCategoryID);
                db.RegisteredUsers.Add(RegisteredUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(RegisteredUser);
        }

        // GET: RegisteredUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisteredUser RegisteredUser = db.RegisteredUsers.Find(id);
            if (RegisteredUser == null)
            {
                return HttpNotFound();
            }
            return View(RegisteredUser);
        }

        // POST: RegisteredUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Firstname,Lastname,Address,City,State,ZipCode,Email,RegisteredUserID")] RegisteredUser RegisteredUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(RegisteredUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(RegisteredUser);
        }

        // GET: RegisteredUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisteredUser RegisteredUser = db.RegisteredUsers.Find(id);
            if (RegisteredUser == null)
            {
                return HttpNotFound();
            }
            return View(RegisteredUser);
        }

        // POST: RegisteredUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RegisteredUser RegisteredUser = db.RegisteredUsers.Find(id);
            db.RegisteredUsers.Remove(RegisteredUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhotoPortfolio/PhotoPortfolio/Controllers/RevenuesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoPortfolio.Models;
using Microsoft.AspNet.Identity;
using System.IO;

namespace PhotoPortfolio.Controllers
{
    public class RevenuesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Revenues
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var RevenueViewModelList = db.RegisteredUsers
                           .Join(db.Revenues,
                           c => c.ID, r => r.RegisteredUserID,
                           (c, r) => new RevenueViewModel
                           {
                               RegisteredUser = c,
                               Total = r.Total,
                               Date = r.Date,
                               RevenueCategory = r.RevenueCategory
                           })
                           .OrderByDescending(x => x.Date)
                           .Take(5).ToList();

           

            ViewBag.rows = db.Revenues.Select(x => x).OrderByDescending(y => y.Date).Take(5);
            ViewBag.dates = db.Revenues.Select(x => x.Date).Distinct().ToList();
            ViewBag.totals = db.Revenues.GroupBy(y => y.Date).Select(x => x.Sum(y => y.Total)).ToArray();
            return View(RevenueViewModelList);
        }

        public ActionResult PartialQuarterly()
        {
            ViewBag.Q1 = db.Revenues
                    .Where(x => x.Date.Month <= 3 && x.Date.Month >= 1)
                    .Select(x => x.Total)
                    .Sum(x => x);
            ViewBag.Q2 = db.Revenues
                    .Where(x => x.Date.Month <= 6 && x.Date.Month >= 4)
                    .Select(x => x.Total)
                    .Sum(x => x);
            ViewBag.Q3 = db.Revenues
                    .Where(x => x.Date.Month <= 9 && x.Date.Month >= 7)
                    .Select(x => x.Total)
                    .Sum(x => x);
            ViewBag.Q4 = db.Revenues
                    .Where(x => x.Date.Month <= 12 && x.Date.Month >= 10)
                    .Select(x => x.Total)
                    .Sum(x => x);
            return PartialView("QuarterlyRevenues");
        }

        public ActionResult Quarterly()
        {
            return View();
        }
        [Authorize(Roles ="admin")]
        public ActionResult BooksPage()
        {
            var RevenueViewModelList = db.RegisteredUsers
                           .Join(db.Revenues,
                           c => c.ID, r => r.RegisteredUserID,
                           (c, r) => new RevenueViewModel
                           {
                               RegisteredUser = c,
                               Total = r.Total,
                               Date = r.Date,
                               RevenueCategory = r.RevenueCategory
                           })
                           .OrderByDescending(x => x.Date)
                           .Take(5).ToList();

            ViewBag.xrows = db.Expenses.Select(x => x).OrderByDescending(y => y.Date).Take(5);
            ViewBag.xdates = db.Expenses.Select(x => x.Date).Distinct().ToList();
            ViewBag.xtotals = db.Expenses.GroupBy(y => y.Date).Select(x => x.Sum(y => y.Total)).ToArray();

            ViewBag.rows = db.Revenues.Select(x => x).OrderByDescending(y => y.Date).Take(5);
            ViewBag.dates = db.Revenues.Select(x => x.Date.Month).Distinct().ToList();
            ViewBag.totals = db.Revenues.GroupBy(y => y.Date.Month).Select(x => x.Sum(y => y.Total)).ToArray();
            return View("BooksPage");
        }


        public ActionResult SaveUploadedFile()
        {
            bool isSavedSuccessfully = true;
            string fName = "";
            try
            {
                foreach (string fileName in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fileName];
                    //Save file content goes here
                    fName = file.FileName;
                    if (file != null && file.ContentLength > 0)
                    {
                        var originalDirectory = new DirectoryInfo(string.Format("{0}Images\\WallImages", Server.MapPath("~/Images/pictures")));
                        string pathString = System.IO.Path.Combine(originalDirectory.ToString(), "imagepath");
                        var fileName1 = Path.GetFileName(file.FileName);
                        bool isExists = System.IO.Directory.Exists(pathString);
                        if (!isExists)
                            System.IO.Directory.CreateDirectory(pathString);
                        var path = string.Format("{0}\\{1}", pathString, file.FileName);
                        file.SaveAs(path);
                    }
                }
            }
            catch (Exception ex)
            {
                isSavedSuccessfully = false;
            }
            if (isSavedSuccessfully)
            {
                return Json(new { Message = fName });
            }
            else
            {
                return Json(new { Message = "Error in saving file" });
            }
        }
        // GET: Revenues/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revenue revenue = db.Revenues.Find(id);
            if (revenue == null)
            {
                return HttpNotFound();
            }
            return View(revenue);
        }
        [Authorize(Roles = "admin")]
        public ActionResult CreatePartial()
        {
            ViewBag.RegisteredUserID = new SelectList(db.RegisteredUsers, "ID", "Firstname");
            ViewBag.RevenueCategoryID = new SelectList(db.RevenueCategories, "ID", "Name");
            return PartialView("Create");
        }

        // GET: Revenues/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        { 
            ViewBag.RegisteredUserID = new SelectList(db.RegisteredUsers, "ID", "Firstname");
            ViewBag.RevenueCategoryID = new SelectList(db.RevenueCategories, "ID", "Name");
            return View();
        }

        // POST: Revenues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "ID, Total, Date, RegisteredUserID, RevenueCategoryID")] Revenue revenue)
        {
            if (ModelState.IsValid)
            {
                //revenue.RegisteredUserID = User.Identity.GetUserId();
                //ViewBag.RevenueCategoryID = new SelectList(db.RevenueCategories, "ID", "Name", revenue.RevenueCategoryID);
                db.Revenues.Add(revenue);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RevenueCategoryID = new SelectList(db.RevenueCategories, "ID", "Name", revenue.RevenueCategoryID);
            ViewBag.RegisteredUserID = new SelectList(db.RegisteredUsers, "ID", "Firstname", revenue.RegisteredUserID);
            return View(revenue);
        }

        // GET: Revenues/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revenue revenue = db.Revenues.Find(id);
            if (revenue == null)
            {
                return HttpNotFound();
            }
            ViewBag.RegisteredUserID = new SelectList(db.RegisteredUsers, "ID", "Firstname", revenue.RegisteredUserID);
            ViewBag.RevenueCategoryID = new SelectList(db.RevenueCategories, "ID", "Name", revenue.RevenueCategoryID);
            return View(revenue);
        }

        // POST: Revenues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "ID,Total,Date,RegisteredUserID,RevenueCategoryID")] Revenue revenue)
        {
            if (ModelState.IsValid)
            {
                db.Entry(revenue).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RegisteredUserID = new SelectList(db.RegisteredUsers, "ID", "Firstname", revenue.RegisteredUserID);
            ViewBag.RevenueCategoryID = new SelectList(db.RevenueCategories, "ID", "Name", revenue.RevenueCategoryID);
            return View(revenue);
        }

        // GET: Revenues/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revenue revenue = db.Revenues.Find(id);
            if (revenue == null)
            {
                return HttpNotFound();
            }
            return View(revenue);
        }

        // POST: Revenues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

PhotoPortfolio/PhotoPortfolio/Views/Revenues/BooksPage.cshtml

@{
    ViewBag.Title = "BooksPage";
}
@Styles.Render("~/Content/css")

<body>
    <h2 style="font-family:'madina_script-webfont'; text-align: center;" >BooksPage</h2>
    <br />
    <br />
    <div class="container-fluid ">
        <div class="container" style="color:red" align="center">
            <div class="col-md-3" style="color:red; width:250px; height:200px; "align="center">
                <button class="btn">Revenues</button>                           
            </div>                                                              
            <div class="col-md-3" style="color:red; width:250px; height:200px; "align="center">
                <button class="btn">Expenses</button>                           
            </div>                                                              
            <div class="col-md-3" style="color:red; width:250px; height:200px; "align="center">
                <input type="button" class="btn" value="Clients" onclick="location.href='@Url.Action("AdminClientControls", "RegisteredUsers")'" />
                @*<button class="btn">Clients</button>*@                            
            </div>                                                              
            <div class="col-md-3" style="color:red; width:250px; height:200px; "align="center">
                <button class="btn bt">Reports</button>
            </div>
        </div>
        <br />
        <br />
        <div class="row" style="text-align:center;">
            <div class="col-md-4">
                <h1> HI Everyone</h1>
                <canvas id="myBarChart"></canvas>
            </div>
            <div class="col-md-4">
                <h1> HI Everyone</h1>
                <canvas id="myLineChart"></canvas>
            </div>
            
        </div>
    </div>


    @{
        double?[] result = ViewBag.totals;
        string test = "";

        for (int i = 0; i < result.Length; i++)
        {
            if (i == 0)
            {
                test = test + result[i].ToString();
            }
            else
            {
                test = test + "," + result[i].ToString();
            }
        }

        var Dates = ViewBag.dates;
        string dateString = "";
        foreach (var item in Dates)
        {
            if (dateString == "")
            {
                dateString = dateString + item;
            }
            else
            {
                dateString = dateString + "," + item;
            }
        }
    }
    <script>
        var result = "@test";
        var resultsArray = result.split(',');
        var somthing = "@dateString";
        var theThing = somthing.split(',');
        var context = $("#myBarChart").get(0).getContext("2d");
        var data = {
            labels: theThing,
            datasets: [{
                label: "My First dataset",
                fillColor: "rgba(39,242,242,0.5)",
                strokeColor: "rgba(220,220,220,0.8)",
                highlightFill: "rgba(255,0,39,0.75)",
                highlightStroke: "rgba(220,220,220,1)",
                data: resultsArray
            }]
        };

        var options = {
            //Boolean - Whether the scale should start at zero, or an order of magnitude down from the lowest value
            scaleBeginAtZero: true,
            //Boolean - Whether grid lines are shown across the chart
            scaleShowGridLines: false,
            //String - Colour of the grid lines
            scaleGridLineColor: "rgba(0,0,0,.05)",
            //Number - Width of the grid lines
            scaleGridLineWidth: 1,
            //Boolean - Whether to show horizontal lines (except X axis)
            scaleShowHorizontalLines: true,
            //Boolean - Whether to show vertical lines (except Y axis)
            scaleShowVerticalLines: true,
            //Boolean - If there is a stroke on each bar
            barShowStroke: true,
            //Number - Pixel width of the bar stroke
            barStrokeWidth: 2,
            //Number - Spacing between each of the X value sets
            barValueSpacing: 5,
            //Number - Spacing between data sets within X values
            barDatasetSpacing: 1,
            //String - A legend template
            legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].fillColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"
        }
        var myBarChart = new Chart(context).Bar(data, options);
    </script>

    @{
        double?[] xresult = ViewBag.xtotals;
        string xtest = "";

        for (int i = 0; i < xresult.Length; i++)
        {
            if (i == 0)
            {
                xtest = xtest + xresult[i].ToString();
            }
            else
            {
                xtest = xtest + "," + xresult[i].ToString();
            }
        }

        var xDates = ViewBag.xdates;
        string xdateString = "";
        foreach (var item in xDates)
        {
            if (dateString == "")
            {
                xdateString = xdateString + item.ToString("dd");
            }
            else
            {
                xdateString = xdateString + "," + item.ToString("dd");
            }
        }
    }
    <script>
        var xresult = "@xtest";
        var xresultsArray = xresult.split(',');
        var xsomthing = "@xdateString";
        var xtheThing = xsomthing.split(',');
        var xcontext = $("#myLineChart").get(0).getContext("2d");
        var linedata = {
            labels: xtheThing,
            datasets: [{
                label: "My First dataset",
                fillColor: "rgba(39,242,242,0.5)",
                strokeColor: "rgba(220,220,220,0.8)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "rgba(255,0,39,0.75)",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: xresultsArray
            }]
        }
        var lineoptions = {
            ///Boolean - Whether grid lines are shown across the chart
            scaleShowGridLines: false,
            //String - Colour of the grid lines
            scaleGridLineColor: "rgba(0,0,0,.05)",
            //Number - Width of the grid lines
            scaleGridLineWidth: 1,
            //Boolean - Whether the line is curved between points
            bezierCurve: true,
            //Number - Tension of the bezier curve between points
            bezierCurveTension: 0.4,
            //Boolean - Whether to show a dot for each point
            pointDot: true,
            //Number - Radius of each point dot in pixels
            pointDotRadius: 4,
            //Number - Pixel width of point dot stroke
            pointDotStrokeWidth: 1,
            //Number - amount extra to add to the radius to cater for hit detection outside the drawn point
            pointHitDetectionRadius: 20,
            //Boolean - Whether to show a stroke for datasets
            datasetStroke: true,
            //Number - Pixel width of dataset stroke
            datasetStrokeWidth: 2,
            //Boolean - Whether to fill the dataset with a colour
            datasetFill: true,
        }
        var myLineChart = new Chart(xcontext).Line(linedata, lineoptions);

        //File Upload response from the server
 
    </script>
  
</body>

PhotoPortfolio/PhotoPortfolio/Views/Revenues/Create.cshtml
@model PhotoPortfolio.Models.Revenue

@{
    ViewBag.Title = "Create";
}
@Styles.Render("~/Content/css")
<h2>Create</h2>

@using (Html.BeginForm("Create", "Revenues"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Revenue</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegisteredUserID, "RegisteredUserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RegisteredUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RegisteredUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RevenueCategoryID, "RevenueCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RevenueCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RevenueCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PhotoPortfolio/PhotoPortfolio/Views/Revenues/Index.cshtml
@*@model IEnumerable<PhotoPortfolio.Models.Revenue>*@

@model IEnumerable<PhotoPortfolio.Models.RevenueViewModel>



<div class="row">
    <div class="col-sm-8 col-sm-offset-2">

    

    
    </div>
</div>

    <div class="row" id="quarterlyRow">
        <div class="col-sm-8 col-sm-offset-2">

        <h1>Quarterly Revenues</h1>
        </div>
        <div id="Quarterly" class="col-sm-8 col-sm-offset-2">

        </div>
    </div>
    
<div class="row" id="graphRow">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Daily Revenues</h1>
        <canvas id="myChart" width="980px" height="auto"></canvas>
    </div>
</div>

<div id="revenueDiv">
    <div id="Div2"></div>
</div>

<div class="panel row">
    <div class="col-sm-6 col-sm-offset-2">
        <div>
            <button class="btn btn-default" id="revenue"><span class="glyphicon glyphicon-plus"></span> Add New Revenue</button>
            <button class="btn btn-default" id="createBtn"><span class="glyphicon glyphicon-plus"></span> Add A Category</button>
        </div>
    <h1>Revenues</h1>
    <table class="col-sm-12" cellpadding="10">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegisteredUser.Firstname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RevenueCategory.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @(item.RegisteredUser.Firstname)
                </td>
                <td>
                    @(item.RevenueCategory.Name)
                </td>
                <td>
                    @(item.Total)
                </td>
                <td>
                    @(item.Date.ToShortDateString())
                </td>
            </tr>
        }
    </table>
    </div>
</div>

@{
    double?[] result = ViewBag.totals;
    string test = "";

    for (int i = 0; i < result.Length; i++)
    {
        if (i == 0)
        {
            test = test + result[i].ToString();
        }
        else
        {
            test = test + "," + result[i].ToString();
        }
    }

    var Dates = ViewBag.dates;
    string dateString = "";
    foreach (var item in Dates)
    {
        if (dateString == "")
        {
            dateString = dateString + item.ToString("dd");
        }
        else
        {
            dateString = dateString + "," + item.ToString("dd");
        }
    }
}

<script>
        var result = "@test";
        var resultsArray = result.split(',');
        var somthing = "@dateString";
        var theThing = somthing.split(',');
        var context = $("#myChart").get(0).getContext("2d");
        var data = {
            labels: theThing,

            datasets: [{

                label: "My First dataset",
                fillColor: "rgba(39,242,242,0.5)",
                strokeColor: "rgba(220,220,220,0.8)",
                highlightFill: "rgba(255,0,39,0.75)",
                highlightStroke: "rgba(220,220,220,1)",
                data: resultsArray
                }]
    };

    var options = {
        //Boolean - Whether the scale should start at zero, or an order of magnitude down from the lowest value
        scaleBeginAtZero: true,

        //Boolean - Whether grid lines are shown across the chart
        scaleShowGridLines: false,

        //String - Colour of the grid lines
        scaleGridLineColor: "rgba(0,0,0,.05)",

        //Number - Width of the grid lines
        scaleGridLineWidth: 1,

        //Boolean - Whether to show horizontal lines (except X axis)
        scaleShowHorizontalLines: true,

        //Boolean - Whether to show vertical lines (except Y axis)
        scaleShowVerticalLines: true,

        //Boolean - If there is a stroke on each bar
        barShowStroke: true,

        //Number - Pixel width of the bar stroke
        barStrokeWidth: 2,

        //Number - Spacing between each of the X value sets
        barValueSpacing: 5,

        //Number - Spacing between data sets within X values
        barDatasetSpacing: 1,

        //String - A legend template
        legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].fillColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"
    }
    var myBarChart = new Chart(context).Bar(data, options);

        $(document).ready(function () {
            var revenue = '@Url.Action("CreatePartial", "Revenues")';
            var createRev = '@Url.Action("CreatePartial", "RevenueCategories")';
            $("#revenue").click(function () {
                $('#revenueDiv').load(revenue, { searchText: "" });
            })
            $("#createBtn").click(function () {
                {
                    $('#revenueDiv').load(createRev, { searchText: "" });
                }
            })
        });

        $(document).ready(function () {
            var revCat = '@Url.Action("PartialQuarterly", "Revenues")';
            $('#Quarterly').load(revCat);

        });

</script>